import type { Metadata } from "next";
import { SITE_URL } from "@/lib/site-config";

export const metadata: Metadata = {
	title: "Privacy Policy",
	description: "Privacy policy for itstarun.fyi portfolio website",
	alternates: {
		canonical: `${SITE_URL}/privacy`,
	},
};

export default function PrivacyPage() {
	return (
		<div className="container mx-auto max-w-4xl px-4 py-16 md:py-20 lg:py-24">
			<span className="eyebrow mb-4 block">Legal</span>
			<h1 className="section-title mb-4">Privacy Policy</h1>

			<p className="section-subtitle mb-12">Last updated: August 10, 2026</p>

			<section className="mb-8 neo-panel p-6">
				<h2 className="mb-4 text-2xl font-semibold">1. Introduction</h2>
				<p className="text-muted-foreground">
					This Privacy Policy explains what information is collected when you
					visit itstarun.fyi and how that information is used.
				</p>
			</section>

			<section className="mb-8 neo-panel p-6">
				<h2 className="mb-4 text-2xl font-semibold">
					2. Information We Collect
				</h2>
				<p className="mb-3 text-muted-foreground">
					The website has no account sign-up flow. Information is collected only
					when you choose to send it.
				</p>
				<ul className="list-disc space-y-2 pl-6 text-muted-foreground">
					<li>
						Contact form submissions: your name, email address, an optional
						subject, and your message
					</li>
					<li>
						Information you voluntarily share when contacting directly by email
						(for example, your email address and message content)
					</li>
					<li>
						Basic technical request data typically generated by web hosting
						infrastructure (for example, IP address, request timestamps, and
						user-agent data)
					</li>
				</ul>
			</section>

			<section className="mb-8 neo-panel p-6">
				<h2 className="mb-4 text-2xl font-semibold">3. Service Providers</h2>
				<p className="mb-3 text-muted-foreground">
					Contact form submissions are not stored in a database on this site.
					They are delivered as an email to the site owner&apos;s inbox through
					Resend, an email delivery provider, which processes the submitted
					fields in order to send that message.
				</p>
				<p className="text-muted-foreground">
					The site is hosted on Vercel, which processes technical request data
					as part of serving the site.
				</p>
			</section>

			<section className="mb-8 neo-panel p-6">
				<h2 className="mb-4 text-2xl font-semibold">4. Cookies and Tracking</h2>
				<p className="text-muted-foreground">
					This website does not currently provide a cookie consent banner and
					does not currently advertise analytics tracking controls. If analytics
					or consent controls are introduced in the future, this policy will be
					updated.
				</p>
			</section>

			<section className="mb-8 neo-panel p-6">
				<h2 className="mb-4 text-2xl font-semibold">
					5. How Information Is Used
				</h2>
				<ul className="list-disc space-y-2 pl-6 text-muted-foreground">
					<li>To read and reply to contact form and direct email inquiries</li>
					<li>To maintain site reliability and security</li>
				</ul>
				<p className="mt-3 text-muted-foreground">
					Your information is not sold, and it is not used for advertising or
					marketing.
				</p>
			</section>

			<section className="mb-8 neo-panel p-6">
				<h2 className="mb-4 text-2xl font-semibold">6. Third-Party Links</h2>
				<p className="text-muted-foreground">
					This site includes links to third-party websites (for example, GitHub,
					LinkedIn, and external project sites). Their privacy practices are
					governed by their own policies.
				</p>
			</section>

			<section className="mb-8 neo-panel p-6">
				<h2 className="mb-4 text-2xl font-semibold">7. Data Retention</h2>
				<p className="text-muted-foreground">
					Contact form submissions and messages sent directly by email arrive in
					an email inbox and are retained only as long as needed to respond and
					maintain reasonable communication history. Resend and Vercel retain
					delivery and request logs according to their own retention schedules.
				</p>
			</section>

			<section className="mb-8 neo-panel p-6">
				<h2 className="mb-4 text-2xl font-semibold">8. Your Rights</h2>
				<p className="mb-3 text-muted-foreground">
					Depending on your jurisdiction, you may request access to, correction
					of, or deletion of personal information you have shared directly.
				</p>
				<p className="text-muted-foreground">
					To request this, contact: <strong>itstarun1994@gmail.com</strong>
				</p>
			</section>

			<section className="mb-8 neo-panel p-6">
				<h2 className="mb-4 text-2xl font-semibold">
					9. Updates to This Policy
				</h2>
				<p className="text-muted-foreground">
					This policy may be revised when site functionality changes. Updates
					will be published on this page with a new revision date.
				</p>
			</section>

			<section className="mb-8 neo-panel p-6">
				<h2 className="mb-4 text-2xl font-semibold">10. Contact</h2>
				<p className="text-muted-foreground">
					For privacy questions, email: <strong>itstarun1994@gmail.com</strong>
				</p>
			</section>
		</div>
	);
}
