import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Privacy Policy - Tarun Portfolio",
	description: "Privacy policy for itstarun.fyi portfolio website",
};

export default function PrivacyPage() {
	return (
		<div className="container mx-auto max-w-4xl px-4 py-12">
			<h1 className="mb-8 text-4xl font-bold">Privacy Policy</h1>

			<p className="mb-8 text-muted-foreground">
				Last updated: February 21, 2026
			</p>

			<section className="mb-8">
				<h2 className="mb-4 text-2xl font-semibold">1. Introduction</h2>
				<p className="text-muted-foreground">
					This Privacy Policy explains what information is collected when you
					visit itstarun.fyi and how that information is used.
				</p>
			</section>

			<section className="mb-8">
				<h2 className="mb-4 text-2xl font-semibold">
					2. Information We Collect
				</h2>
				<p className="mb-3 text-muted-foreground">
					The website does not include a contact form or account sign-up flow.
					You can reach out directly by email.
				</p>
				<ul className="list-disc space-y-2 pl-6 text-muted-foreground">
					<li>
						Information you voluntarily share when contacting via email (for
						example, your email address and message content)
					</li>
					<li>
						Basic technical request data typically generated by web hosting
						infrastructure (for example, request timestamps and user-agent data)
					</li>
				</ul>
			</section>

			<section className="mb-8">
				<h2 className="mb-4 text-2xl font-semibold">3. Cookies and Tracking</h2>
				<p className="text-muted-foreground">
					This website does not currently provide a cookie consent banner and
					does not currently advertise analytics tracking controls. If analytics
					or consent controls are introduced in the future, this policy will be
					updated.
				</p>
			</section>

			<section className="mb-8">
				<h2 className="mb-4 text-2xl font-semibold">
					4. How Information Is Used
				</h2>
				<ul className="list-disc space-y-2 pl-6 text-muted-foreground">
					<li>To respond to direct email inquiries</li>
					<li>To maintain site reliability and security</li>
				</ul>
			</section>

			<section className="mb-8">
				<h2 className="mb-4 text-2xl font-semibold">5. Third-Party Links</h2>
				<p className="text-muted-foreground">
					This site includes links to third-party websites (for example, GitHub,
					LinkedIn, and external project sites). Their privacy practices are
					governed by their own policies.
				</p>
			</section>

			<section className="mb-8">
				<h2 className="mb-4 text-2xl font-semibold">6. Data Retention</h2>
				<p className="text-muted-foreground">
					Messages sent directly by email are retained only as long as needed to
					respond and maintain reasonable communication history.
				</p>
			</section>

			<section className="mb-8">
				<h2 className="mb-4 text-2xl font-semibold">7. Your Rights</h2>
				<p className="mb-3 text-muted-foreground">
					Depending on your jurisdiction, you may request access to, correction
					of, or deletion of personal information you have shared directly.
				</p>
				<p className="text-muted-foreground">
					To request this, contact: <strong>itstarun1994@gmail.com</strong>
				</p>
			</section>

			<section className="mb-8">
				<h2 className="mb-4 text-2xl font-semibold">
					8. Updates to This Policy
				</h2>
				<p className="text-muted-foreground">
					This policy may be revised when site functionality changes. Updates
					will be published on this page with a new revision date.
				</p>
			</section>

			<section className="mb-8">
				<h2 className="mb-4 text-2xl font-semibold">9. Contact</h2>
				<p className="text-muted-foreground">
					For privacy questions, email: <strong>itstarun1994@gmail.com</strong>
				</p>
			</section>
		</div>
	);
}
