import type { Metadata } from "next";
import {
	OG_IMAGE_SIZE,
	SITE_NAME,
	SITE_URL,
	TWITTER_HANDLE,
} from "@/lib/site-config";

const canonical = `${SITE_URL}/privacy`;
const description =
	"What itstarun.fyi collects and what it does not. No cookies, no ad tech, no cross-site tracking — cookieless aggregate page counts and the messages you send me.";
const socialTitle = "Privacy Policy - itstarun.fyi";

export const metadata: Metadata = {
	title: "Privacy Policy - No Cookies, No Cross-Site Tracking",
	description,
	alternates: {
		canonical,
	},
	openGraph: {
		type: "website",
		locale: "en_US",
		url: canonical,
		title: socialTitle,
		description,
		siteName: SITE_NAME,
		// Unlike /about, /contact and /projects this route has no
		// opengraph-image.tsx of its own, and declaring openGraph here replaces
		// the root object outright — so name the site-wide card explicitly.
		images: [
			{
				url: "/opengraph-image",
				...OG_IMAGE_SIZE,
				alt: SITE_NAME,
			},
		],
	},
	twitter: {
		card: "summary_large_image",
		title: socialTitle,
		description,
		creator: TWITTER_HANDLE,
		site: TWITTER_HANDLE,
	},
};

export default function PrivacyPage() {
	return (
		<div className="container mx-auto max-w-4xl px-4 py-16 md:py-20 lg:py-24">
			<span className="eyebrow mb-4 block">Legal</span>
			<h1 className="section-title mb-4">Privacy Policy</h1>

			<p className="section-subtitle mb-12">Last updated: August 10, 2026</p>

			<section className="mb-8 neo-panel p-6">
				<h2 className="mb-4 text-2xl font-semibold">1. Introduction</h2>
				<p className="text-muted-foreground">
					This Privacy Policy explains what information is collected when you
					visit itstarun.fyi and how that information is used.
				</p>
			</section>

			<section className="mb-8 neo-panel p-6">
				<h2 className="mb-4 text-2xl font-semibold">
					2. Information We Collect
				</h2>
				<p className="mb-3 text-muted-foreground">
					The website has no account sign-up flow. Information is collected only
					when you choose to send it.
				</p>
				<ul className="list-disc space-y-2 pl-6 text-muted-foreground">
					<li>
						Contact form submissions: your name, email address, an optional
						subject, and your message
					</li>
					<li>
						Information you voluntarily share when contacting directly by email
						(for example, your email address and message content)
					</li>
					<li>
						Basic technical request data typically generated by web hosting
						infrastructure (for example, IP address, request timestamps, and
						user-agent data)
					</li>
				</ul>
			</section>

			<section className="mb-8 neo-panel p-6">
				<h2 className="mb-4 text-2xl font-semibold">3. Service Providers</h2>
				<p className="mb-3 text-muted-foreground">
					Contact form submissions are not stored in a database on this site.
					They are delivered as an email to the site owner&apos;s inbox through
					Resend, an email delivery provider, which processes the submitted
					fields in order to send that message.
				</p>
				<p className="text-muted-foreground">
					The site is hosted on Vercel, which processes technical request data
					as part of serving the site, and also provides the cookieless
					analytics and performance measurement described in section 4.
				</p>
			</section>

			<section className="mb-8 neo-panel p-6">
				<h2 className="mb-4 text-2xl font-semibold">4. Cookies and Tracking</h2>
				<p className="mb-3 text-muted-foreground">
					This site sets no cookies at all &mdash; none for tracking, none for
					advertising, none for sessions. There is no ad tech, no advertising
					network, no data broker, and nothing that follows you to other
					websites. That is why you see no cookie banner: there is nothing to
					consent to.
				</p>
				<p className="mb-3 text-muted-foreground">
					It does measure two things, both cookieless and both aggregate. Vercel
					Analytics counts page views, and Vercel Speed Insights records how
					quickly pages load. Between them they see the page you viewed, the
					site that referred you, your approximate country, and your device,
					browser and operating system type. They do not see your IP address,
					build a profile, or store an identifier on your device, and their
					scripts are served from this domain rather than a third-party one.
				</p>
				<p className="mb-3 text-muted-foreground">
					The one thing stored in your browser is your light or dark theme
					preference, kept in localStorage. It is written only if you use the
					theme toggle &mdash; visiting the site without touching it stores
					nothing. It stays on your device and is never sent anywhere.
				</p>
				<p className="text-muted-foreground">
					If this ever changes &mdash; if a cookie, a consent control or any
					identifying measurement is introduced &mdash; this policy will be
					updated before it ships.
				</p>
			</section>

			<section className="mb-8 neo-panel p-6">
				<h2 className="mb-4 text-2xl font-semibold">
					5. How Information Is Used
				</h2>
				<ul className="list-disc space-y-2 pl-6 text-muted-foreground">
					<li>To read and reply to contact form and direct email inquiries</li>
					<li>To maintain site reliability and security</li>
				</ul>
				<p className="mt-3 text-muted-foreground">
					Your information is not sold, and it is not used for advertising or
					marketing.
				</p>
			</section>

			<section className="mb-8 neo-panel p-6">
				<h2 className="mb-4 text-2xl font-semibold">6. Third-Party Links</h2>
				<p className="text-muted-foreground">
					This site includes links to third-party websites (for example, GitHub,
					LinkedIn, and external project sites). Their privacy practices are
					governed by their own policies.
				</p>
			</section>

			<section className="mb-8 neo-panel p-6">
				<h2 className="mb-4 text-2xl font-semibold">7. Data Retention</h2>
				<p className="text-muted-foreground">
					Contact form submissions and messages sent directly by email arrive in
					an email inbox and are retained only as long as needed to respond and
					maintain reasonable communication history. Resend and Vercel retain
					delivery and request logs according to their own retention schedules.
				</p>
			</section>

			<section className="mb-8 neo-panel p-6">
				<h2 className="mb-4 text-2xl font-semibold">8. Your Rights</h2>
				<p className="mb-3 text-muted-foreground">
					Depending on your jurisdiction, you may request access to, correction
					of, or deletion of personal information you have shared directly.
				</p>
				<p className="text-muted-foreground">
					To request this, contact: <strong>itstarun1994@gmail.com</strong>
				</p>
			</section>

			<section className="mb-8 neo-panel p-6">
				<h2 className="mb-4 text-2xl font-semibold">
					9. Updates to This Policy
				</h2>
				<p className="text-muted-foreground">
					This policy may be revised when site functionality changes. Updates
					will be published on this page with a new revision date.
				</p>
			</section>

			<section className="mb-8 neo-panel p-6">
				<h2 className="mb-4 text-2xl font-semibold">10. Contact</h2>
				<p className="text-muted-foreground">
					For privacy questions, email: <strong>itstarun1994@gmail.com</strong>
				</p>
			</section>
		</div>
	);
}
